# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
from datetime import datetime

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('../../src'))

# -- Project information -----------------------------------------------------

project = 'OptiX'
copyright = f'{datetime.now().year}, Tolga BERBER, Beyzanur SİYAH'
author = 'Tolga BERBER, Beyzanur SİYAH'

# The full version, including alpha/beta/rc tags
release = '1.0.0'
version = '1.0'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinx.ext.napoleon',
    'sphinx_rtd_theme',
    'sphinx_copybutton',
    'sphinx_tabs.tabs',
    'myst_parser',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['../_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The suffix(es) of source filenames.
source_suffix = {
    '.rst': None,
    '.md': 'myst_parser',
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.
html_theme_options = {
    'analytics_id': '',
    'analytics_anonymize_ip': False,
    'logo_only': True,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    'style_nav_header_background': '#2980B9',
    # Toc options
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['../_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
html_sidebars = {
    '**': [
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = '../_static/optix_logo.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.
html_favicon = '../_static/favicon.ico'

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
html_use_smartypants = True

# Custom CSS files
html_css_files = [
    'css/custom.css',
    'css/optix_theme.css',
]

# Custom JavaScript files
html_js_files = [
    'js/custom.js',
]

# -- Options for LaTeX output ------------------------------------------------

latex_engine = 'xelatex'

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '11pt',

    # Additional stuff for the LaTeX preamble.
    'preamble': r'''
% Modern fonts with comprehensive fallbacks
\usepackage{fontspec}
\usepackage{unicode-math}
\defaultfontfeatures{Ligatures=TeX}

% Main font with fallbacks
\IfFontExistsTF{Inter}{
  \setmainfont{Inter}[
    UprightFont = *-Regular,
    BoldFont = *-Bold,
    ItalicFont = *-Italic,
    BoldItalicFont = *-BoldItalic
  ]
}{
  \IfFontExistsTF{SF Pro Text}{
    \setmainfont{SF Pro Text}
  }{
    \IfFontExistsTF{Segoe UI}{
      \setmainfont{Segoe UI}
    }{
      \IfFontExistsTF{Helvetica Neue}{
        \setmainfont{Helvetica Neue}
      }{
        % Final fallback to system default
      }
    }
  }
}

% Sans font with fallbacks
\IfFontExistsTF{Inter}{
  \setsansfont{Inter}[
    UprightFont = *-Regular,
    BoldFont = *-Bold,
    ItalicFont = *-Italic,
    BoldItalicFont = *-BoldItalic
  ]
}{
  \IfFontExistsTF{SF Pro Display}{
    \setsansfont{SF Pro Display}
  }{
    \IfFontExistsTF{Segoe UI}{
      \setsansfont{Segoe UI}
    }{
      \IfFontExistsTF{Arial}{
        \setsansfont{Arial}
      }{
        % Final fallback to system default
      }
    }
  }
}

% Monospace font with fallbacks
\IfFontExistsTF{JetBrains Mono}{
  \setmonofont{JetBrains Mono}[
    Scale=0.85,
    UprightFont = *-Regular,
    BoldFont = *-Bold,
    ItalicFont = *-Italic,
    BoldItalicFont = *-BoldItalic
  ]
}{
  \IfFontExistsTF{Fira Code}{
    \setmonofont{Fira Code}[Scale=0.85]
  }{
    \IfFontExistsTF{SF Mono}{
      \setmonofont{SF Mono}[Scale=0.85]
    }{
      \IfFontExistsTF{Consolas}{
        \setmonofont{Consolas}[Scale=0.85]
      }{
        \IfFontExistsTF{Monaco}{
          \setmonofont{Monaco}[Scale=0.85]
        }{
          % Final fallback to system default monospace
        }
      }
    }
  }
}

% Essential packages
\usepackage{amsmath,amsfonts,amssymb}
\usepackage{graphicx}
\usepackage{fancyhdr}
\usepackage{geometry}
\usepackage{xcolor}
\usepackage{tcolorbox}
\usepackage{listings}
\usepackage{hyperref}
\usepackage{tikz}
\usepackage{pgfplots}
\usepackage{booktabs}
\usepackage{multirow}
\usepackage{array}
\usepackage{microtype}
\usepackage{soul}

% Emoji support for XeLaTeX
% Note: XeLaTeX handles Unicode emojis directly through fontspec
% Most system fonts include basic emoji support

% Modern color scheme - 2024 palette
\definecolor{optixblue}{RGB}{0,102,255}
\definecolor{optixcyan}{RGB}{0,217,255}
\definecolor{optixpurple}{RGB}{102,126,234}
\definecolor{optixgreen}{RGB}{0,200,150}
\definecolor{optixorange}{RGB}{255,184,0}
\definecolor{optixred}{RGB}{255,71,87}
\definecolor{optixdark}{RGB}{10,14,39}
\definecolor{optixdarker}{RGB}{5,8,22}
\definecolor{optixlight}{RGB}{247,249,252}
\definecolor{optixlighter}{RGB}{255,255,255}
\definecolor{optixgray}{RGB}{108,114,147}
\definecolor{optixgraydark}{RGB}{75,85,116}
\definecolor{optixbg}{RGB}{248,250,252}
\definecolor{optixaccent1}{RGB}{79,172,254}
\definecolor{optixaccent2}{RGB}{245,87,108}

% Configure hyperref
\hypersetup{
    colorlinks=true,
    linkcolor=optixblue,
    filecolor=optixgreen,
    urlcolor=optixblue,
    citecolor=optixred,
    pdftitle={OptiX Mathematical Optimization Framework},
    pdfauthor={Tolga BERBER, Beyzanur SİYAH},
    pdfsubject={Mathematical Optimization Library Documentation},
    pdfkeywords={optimization, linear programming, constraint satisfaction}
}

% Ultra-modern title page with geometric design
\makeatletter
\renewcommand{\maketitle}{%
  \begin{titlepage}%
    \newgeometry{margin=0cm}
    \begin{tikzpicture}[remember picture,overlay]
      % Modern gradient background
      \fill[optixdarker] (current page.north west) rectangle (current page.south east);
      
      % Geometric shapes and gradients
      \begin{scope}[blend mode=multiply, opacity=0.8]
        \fill[optixblue] (current page.north west) 
          -- ([xshift=8cm]current page.north west) 
          -- ([xshift=12cm,yshift=-8cm]current page.north west) 
          -- ([yshift=-12cm]current page.north west) 
          -- cycle;
      \end{scope}
      
      \begin{scope}[blend mode=screen, opacity=0.6]
        \fill[optixcyan] ([xshift=5cm,yshift=-3cm]current page.north east) circle (4cm);
        \fill[optixpurple] ([xshift=-8cm,yshift=-15cm]current page.north east) circle (6cm);
      \end{scope}
      
      % Subtle dot pattern
      \foreach \x in {0,0.5,...,21} {
        \foreach \y in {0,0.5,...,29.7} {
          \fill[white, opacity=0.02] (\x,\y) circle (0.5pt);
        }
      }
      
      % Glass morphism effect containers
      \begin{scope}[blend mode=normal]
        % Main content container
        \fill[white, opacity=0.05] 
          ([xshift=2cm,yshift=-8cm]current page.north west) 
          rectangle ([xshift=-2cm,yshift=4cm]current page.south east);
        \draw[white, opacity=0.2, line width=1pt] 
          ([xshift=2cm,yshift=-8cm]current page.north west) 
          rectangle ([xshift=-2cm,yshift=4cm]current page.south east);
      \end{scope}
    \end{tikzpicture}
    
    % Content positioning
    \vspace*{6cm}
    \begin{center}%
      % Logo with modern styling
      {\color{white}
        \includegraphics[width=0.25\textwidth]{optix_logo_large.png}
      }\\[2cm]
      
      % Main title with modern typography
      {\fontsize{56}{68}\selectfont\bfseries
       \color{white}
       \textls[150]{OPTIX}}\\[0.8cm]
      
      % Subtitle with accent
      {\fontsize{18}{22}\selectfont
       \color{optixcyan}
       \textls[100]{MATHEMATICAL OPTIMIZATION FRAMEWORK}}\\[3cm]
      
      % Modern info card
      \begin{tikzpicture}
        \node[
          rectangle,
          rounded corners=20pt,
          fill=white,
          fill opacity=0.95,
          text opacity=1,
          drop shadow={
            shadow xshift=0pt,
            shadow yshift=-8pt,
            shadow blur radius=20pt,
            fill opacity=0.3
          },
          minimum width=12cm,
          minimum height=6cm
        ] {
          \begin{minipage}{10cm}
            \centering
            {\fontsize{24}{30}\selectfont\bfseries\color{optixdark}
             Documentation}\\[1cm]
            {\fontsize{14}{18}\selectfont\color{optixgraydark}
             Version \py@release}\\[0.8cm]
            {\fontsize{12}{16}\selectfont\color{optixgraydark}
             \@author}\\[0.5cm]
            {\fontsize{12}{16}\selectfont\color{optixgray}
             \@date}
          \end{minipage}
        };
      \end{tikzpicture}
    \end{center}%
    \restoregeometry
  \end{titlepage}%
}
\makeatother

% Ultra-modern headers and footers
\pagestyle{fancy}
\fancyhf{}
% Header with modern styling
\fancyhead[LE]{%
  \begin{tikzpicture}[baseline=(current bounding box.center)]
    \node[
      rectangle,
      rounded corners=8pt,
      fill=optixblue,
      text=white,
      font=\bfseries\small,
      inner sep=8pt,
      minimum height=16pt
    ] {\thepage};
  \end{tikzpicture}%
  \hspace{10pt}%
  {\color{optixgraydark}\small\leftmark}%
}
\fancyhead[RO]{%
  {\color{optixgraydark}\small\rightmark}%
  \hspace{10pt}%
  \begin{tikzpicture}[baseline=(current bounding box.center)]
    \node[
      rectangle,
      rounded corners=8pt,
      fill=optixblue,
      text=white,
      font=\bfseries\small,
      inner sep=8pt,
      minimum height=16pt
    ] {\thepage};
  \end{tikzpicture}%
}
% Modern footer
\fancyfoot[C]{%
  \begin{tikzpicture}
    \node[
      rectangle,
      rounded corners=12pt,
      fill=optixbg,
      draw=optixblue,
      draw opacity=0.3,
      text=optixgraydark,
      font=\footnotesize,
      inner sep=6pt
    ] {OptiX Mathematical Optimization Framework};
  \end{tikzpicture}%
}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

% Ultra-modern code highlighting
\lstset{
    basicstyle=\ttfamily\footnotesize,
    keywordstyle=\color{optixblue}\bfseries,
    commentstyle=\color{optixgray}\itshape,
    stringstyle=\color{optixgreen},
    numberstyle=\tiny\color{optixgray},
    numbers=left,
    frame=single,
    framerule=0pt,
    breaklines=true,
    showstringspaces=false,
    tabsize=4,
    backgroundcolor=\color{optixdarker},
    basicstyle=\color{optixlighter}\ttfamily\footnotesize,
    keywordstyle=\color{optixcyan}\bfseries,
    commentstyle=\color{optixgray}\itshape,
    stringstyle=\color{optixgreen},
    numberstyle=\tiny\color{optixgray},
    rulecolor=\color{optixblue},
    xleftmargin=0pt,
    framexleftmargin=15pt,
    framexrightmargin=0pt,
    framextopmargin=8pt,
    framexbottommargin=8pt,
    aboveskip=1.5cm,
    belowskip=1cm,
    captionpos=t
}

% Ultra-modern tcolorbox settings
\tcbuselibrary{skins,breakable}
\newtcolorbox{modernbox}[2][]{
  enhanced,
  colback=white,
  colframe=optixblue,
  fonttitle=\bfseries\color{white},
  title=#2,
  arc=12pt,
  boxrule=2pt,
  left=8pt,
  right=8pt,
  top=8pt,
  bottom=8pt,
  breakable,
  #1
}

% Ultra-modern section formatting
\usepackage{titlesec}
\titleformat{\chapter}[display]
  {\normalfont\huge\bfseries\color{optixdark}}
  {\tikz[baseline=(current bounding box.center)]{
     \node[
       rectangle,
       rounded corners=8pt,
       fill=optixblue,
       text=white,
       font=\Large\bfseries,
       inner sep=12pt
     ] {\chaptertitlename\ \thechapter};
   }}
  {20pt}
  {\Huge\color{optixdark}}

\titleformat{\section}
  {\normalfont\Large\bfseries\color{optixdark}}
  {\tikz[baseline=(current bounding box.center)]{
     \node[
       circle,
       fill=optixblue,
       text=white,
       font=\bfseries,
       inner sep=8pt,
       minimum size=24pt
     ] {\thesection};
   }\hspace{10pt}}
  {0pt}
  {}

\titleformat{\subsection}
  {\normalfont\large\bfseries\color{optixpurple}}
  {\tikz[baseline=(current bounding box.center)]{
     \node[
       rectangle,
       rounded corners=4pt,
       fill=optixpurple,
       text=white,
       font=\small\bfseries,
       inner sep=4pt,
       minimum height=16pt
     ] {\thesubsection};
   }\hspace{8pt}}
  {0pt}
  {}

% Modern table styling with glassmorphism
\renewcommand{\arraystretch}{1.4}
\arrayrulecolor{optixblue!30}

% Modern admonitions
\newtcolorbox{note}{
  enhanced,
  colback=optixblue!5,
  colframe=optixblue,
  leftrule=4pt,
  rightrule=0pt,
  toprule=0pt,
  bottomrule=0pt,
  arc=8pt,
  outer arc=8pt,
  fonttitle=\bfseries\color{optixblue},
  title=Note,
  left=8pt,
  right=8pt,
  top=8pt,
  bottom=8pt
}

\newtcolorbox{warning}{
  enhanced,
  colback=optixorange!5,
  colframe=optixorange,
  leftrule=4pt,
  rightrule=0pt,
  toprule=0pt,
  bottomrule=0pt,
  arc=8pt,
  outer arc=8pt,
  fonttitle=\bfseries\color{optixorange},
  title=Warning,
  left=8pt,
  right=8pt,
  top=8pt,
  bottom=8pt
}
''',

    # Latex figure (float) alignment
    'figure_align': 'htbp',

    # Additional LaTeX markup for the footer
    'footer': r'''
\makeatletter
\fancypagestyle{normal}{
    \fancyhf{}
    \fancyfoot[LE,RO]{{\py@HeaderFamily\thepage}}
    \fancyfoot[LO]{{\py@HeaderFamily\nouppercase{\rightmark}}}
    \fancyfoot[RE]{{\py@HeaderFamily\nouppercase{\leftmark}}}
    \fancyhead[LE]{{\py@HeaderFamily \@title, \py@release}}
    \fancyhead[RO]{{\py@HeaderFamily \@title, \py@release}}
    \renewcommand{\headrulewidth}{0.4pt}
    \renewcommand{\footrulewidth}{0.4pt}
}
\makeatother
''',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'OptiX.tex', 'OptiX Mathematical Optimization Framework Documentation',
     'Tolga BERBER, Beyzanur SİYAH', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = '../_static/optix_logo_large.png'

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
latex_use_parts = False

# If true, show page references after internal links.
latex_show_pagerefs = True

# If true, show URL addresses after external links.
latex_show_urls = 'footnote'

# Documents to append as an appendix to all manuals.
latex_appendices = []

# If false, no module index is generated.
latex_domain_indices = True

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'optix', 'OptiX Mathematical Optimization Framework Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'OptiX', 'OptiX Mathematical Optimization Framework Documentation',
     author, 'OptiX', 'Mathematical optimization framework for Python.',
     'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
texinfo_appendices = []

# If false, no module index is generated.
texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
texinfo_show_urls = 'footnote'

# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'ortools': ('https://developers.google.com/optimization/', None),
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for autodoc extension -------------------------------------------

# This value selects if automatically documented members are sorted alphabetical (value 'alphabetical'), 
# by member type (value 'groupwise') or by source order (value 'bysource'). The default is alphabetical.
autodoc_member_order = 'bysource'

# This value is a list of autodoc directive flags that should be automatically applied to all autodoc directives.
autodoc_default_flags = ['members', 'undoc-members', 'show-inheritance']

# If true, autodoc will generate document for the members of the target module.
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# -- Options for autosummary extension ---------------------------------------

# If true, autosummary will generate documents for the members listed in autosummary directive.
autosummary_generate = True

# If true, autosummary will import the modules and extract the docstrings.
autosummary_imported_members = True

# -- Options for Napoleon extension ------------------------------------------

# Enable parsing of NumPy and Google style docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# -- Options for copybutton extension ----------------------------------------

# Exclude copy button from certain code blocks
copybutton_exclude = '.linenos, .gp, .go'

# Custom CSS selectors for copy button
copybutton_selector = "div:not(.no-copy)>div.highlight pre"

# Prompt text to strip from beginning of copied text
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True

# Custom copy button text
copybutton_copy_text = "📋"
copybutton_copied_text = "✅"